<div class="contain-to-grid sticky">
  <div class="row">
    <div class="sixteen columns">
      <nav class="top-bar">
        <ul>
          <li class="name"><h1><a href="/"><img src="/images/logo-marka2.png"></a></h1></li>
          <li class="toggle-topbar"><a href="#"></a></li>
        </ul>
        <section>
          <ul class="left">
            <li><a href="/advantages">Advantages</a></li>
            <li><a href="/services">Services</a></li> 
            <li><a href="/products">Products</a></li>
            <li><a href="/quality">Quality</a></li>
            <li><a href="/sustainability">Sustainability</a></li>
            <li><a href="/team">Team</a></li>
            <li><a href="/news">News</a></li>
            <li><a href="/contact">Contact Us</a></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
</div>